data = input("Enter a string : ")
print("Data's length is ", len(data))

number1 = input("Enter number 1: ")
number2 = input("Enter number 2: ")
print("The sum is: ", int(number1) + int(number2))

data = input("Enter a new string : ")
data = data.replace("a", "*")
data = data.replace("e", "*")
data = data.replace("i", "*")
data = data.replace("o", "*")
data = data.replace("u", "*")
data = data.replace("A", "*")
data = data.replace("E", "*")
data = data.replace("I", "*")
data = data.replace("O", "*")
data = data.replace("U", "*")

print("Replaced data is ", data)
